disable workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,58 +1,58 @@
-name: Test TraceML Across Python Versions & Architectures
-
-on:
-  push:
-    branches:
-      - '**'
-  pull_request:
-  workflow_dispatch:
-
-jobs:
-  test:
-    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          # Ubuntu = x86_64
-          - ubuntu-latest
-
-          # macOS ARM CPUs (Apple Silicon: M1, M2, M3, M4, M5…)
-          - macos-14
-
-          # Windows = x86_64
-          - windows-latest
-
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Upgrade pip + build tools
-        run: |
-          python -m pip install --upgrade pip wheel setuptools
-
-      - name: Install TraceML using pyproject.toml
-        run: |
-          pip install .
-
-      - name: Verify import
-        run: |
-          python -c "import traceml; print('Import OK')"
-
-      - name: Test CLI
-        run: |
-          traceml --help || true
-
-      - name: Run pytest (if exists)
-        run: |
-          pip install pytest
-          pytest -q || true
+#name: Test TraceML Across Python Versions & Architectures
+#
+#on:
+#  push:
+#    branches:
+#      - '**'
+#  pull_request:
+#  workflow_dispatch:
+#
+#jobs:
+#  test:
+#    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
+#    runs-on: ${{ matrix.os }}
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os:
+#          # Ubuntu = x86_64
+#          - ubuntu-latest
+#
+#          # macOS ARM CPUs (Apple Silicon: M1, M2, M3, M4, M5…)
+#          - macos-14
+#
+#          # Windows = x86_64
+#          - windows-latest
+#
+#        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Setup Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#
+#      - name: Upgrade pip + build tools
+#        run: |
+#          python -m pip install --upgrade pip wheel setuptools
+#
+#      - name: Install TraceML using pyproject.toml
+#        run: |
+#          pip install .
+#
+#      - name: Verify import
+#        run: |
+#          python -c "import traceml; print('Import OK')"
+#
+#      - name: Test CLI
+#        run: |
+#          traceml --help || true
+#
+#      - name: Run pytest (if exists)
+#        run: |
+#          pip install pytest
+#          pytest -q || true
